export const mongoErrors = Object.freeze({
  MongoServerError: 'MongoServerError',
  ValidationError: 'ValidationError',
  CastError: 'CastError',
  SyncIndexesError: 'SyncIndexesError',
  DisconnectedError: 'DisconnectedError',
  DivergentArrayError: 'DivergentArrayError',
  MissingSchemaError: 'MissingSchemaError',
  DocumentNotFoundError: 'DocumentNotFoundError',
  ObjectExpectedError: 'ObjectExpectedError',
  ObjectParameterError: 'ObjectParameterError',
  OverwriteModelError: 'OverwriteModelError',
  ParallelSaveError: 'ParallelSaveError',
  ParallelValidateError: 'ParallelValidateError',
  MongooseServerSelectionError: 'MongooseServerSelectionError',
  StrictModeError: 'StrictModeError',
  ValidatorError: 'ValidatorError',
  VersionError: 'VersionError',
})
